### ISSUE TITLE
Update Description and Code for latest jsoncpp release

### ISSUE THREAD

**Issue by JoebRogers** [lxndrdagreat/tiledjson#1]
Hi there,

I just downloaded tiledjson since I figured there was no point in reinventing the wheel if a suitable library already exists for my needs.

However, in order to work with the latest version of jsoncpp, JsonTMXImporter.cpp needs to be updated at lines 49 and 152 to fix a compile error to what I'm assuming was a type deprecation in how their classes worked.

The fix is to replace JSON::ValueIterator with JSON::Value::const_iterator and that does the trick just fine.

Another quick issue I discovered whilst trying to import my file is that the instructions for importing a json map is different to what is listed in the readme. It seems that you can no longer pass in a filepath to the TiledMap constructor, instead you have to create the TiledMap and call loadFromFile ( filepath ) instead.

That's all I've noticed so far!

Thanks.

**Comment by lxndrdagreat** [comment]
Thanks for letting me know! I haven't been actively working in C++ for a while, so I haven't been maintaining this lately. I'll get it updated soon.

**Comment by lxndrdagreat** [comment]
I've updated `JsonTMXImporter` to work with the newer version of jsoncpp. I've also updated the instructions in the README to better reflect how to use tiledjson.
